# Generated by Django 6.0.5 on 2026-06-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_systemconfiguration_actionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='user_role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='interventioncase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='interventioncase',
            name='risk_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='interventioncase',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Alert'), ('IN_REVIEW', 'In Review'), ('INTERVENTION', 'Intervention Planned'), ('FOLLOW_UP_MISSED', 'Missed Follow-up'), ('RESOLVED', 'Resolved')], db_index=True, default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_level',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
